# Generated by Django 3.2 on 2023-10-31 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='name',
            new_name='area_name',
        ),
    ]
