# Generated by Django 3.2 on 2023-10-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0002_rename_name_area_area_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='alignment',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('queued', 'Queued'), ('wip', 'WIP'), ('failed', 'Failed'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='clean',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('queued', 'Queued'), ('wip', 'WIP'), ('failed', 'Failed'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='export',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('queued', 'Queued'), ('wip', 'WIP'), ('failed', 'Failed'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='imported',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('queued', 'Queued'), ('wip', 'WIP'), ('failed', 'Failed'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='point_cloud',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('queued', 'Queued'), ('wip', 'WIP'), ('failed', 'Failed'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='processed',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('queued', 'Queued'), ('wip', 'WIP'), ('failed', 'Failed'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='registered',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('queued', 'Queued'), ('wip', 'WIP'), ('failed', 'Failed'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='upload',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('queued', 'Queued'), ('wip', 'WIP'), ('failed', 'Failed'), ('completed', 'Completed')], max_length=20),
        ),
    ]
