# Generated by Django 3.2 on 2023-10-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0003_auto_20231031_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='alignment',
            field=models.CharField(choices=[('Legacy', 'Legacy'), ('Queued', 'Queued')], max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='clean',
            field=models.CharField(choices=[('Legacy', 'Legacy'), ('Queued', 'Queued')], max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='export',
            field=models.CharField(choices=[('Legacy', 'Legacy'), ('Queued', 'Queued')], max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='imported',
            field=models.CharField(choices=[('Legacy', 'Legacy'), ('Queued', 'Queued')], max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='point_cloud',
            field=models.CharField(choices=[('Legacy', 'Legacy'), ('Queued', 'Queued')], max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='processed',
            field=models.CharField(choices=[('Legacy', 'Legacy'), ('Queued', 'Queued')], max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='registered',
            field=models.CharField(choices=[('Legacy', 'Legacy'), ('Queued', 'Queued')], max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='upload',
            field=models.CharField(choices=[('Legacy', 'Legacy'), ('Queued', 'Queued')], max_length=20),
        ),
    ]
