# Generated by Django 3.2 on 2023-10-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0006_auto_20231031_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='export',
            new_name='exported',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='upload',
            new_name='uploaded',
        ),
    ]
