# Generated by Django 3.2 on 2023-10-31 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0008_auto_20231031_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='area_name',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='status',
            name='alignment',
        ),
        migrations.RemoveField(
            model_name='status',
            name='clean',
        ),
        migrations.RemoveField(
            model_name='status',
            name='exported',
        ),
        migrations.RemoveField(
            model_name='status',
            name='point_cloud',
        ),
        migrations.RemoveField(
            model_name='status',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='status',
            name='registered',
        ),
        migrations.RemoveField(
            model_name='status',
            name='uploaded',
        ),
    ]
