# Generated by Django 3.2 on 2023-10-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0009_auto_20231031_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
