# Generated by Django 3.2 on 2023-10-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0011_rename_area_status_area_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='aligned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
