# Generated by Django 3.2 on 2023-10-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0012_auto_20231031_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='cleaned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='exported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='point_cloud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
