# Generated by Django 3.2 on 2023-11-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0016_auto_20231031_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='aligned',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Failed', 'Failed'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed')], default='No Data', max_length=20),
        ),
        migrations.AddField(
            model_name='area',
            name='cleaned',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Failed', 'Failed'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed')], default='No Data', max_length=20),
        ),
        migrations.AddField(
            model_name='area',
            name='exported',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Failed', 'Failed'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed')], default='No Data', max_length=20),
        ),
        migrations.AddField(
            model_name='area',
            name='imported',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Failed', 'Failed'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed')], default='No Data', max_length=20),
        ),
        migrations.AddField(
            model_name='area',
            name='point_cloud',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Failed', 'Failed'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed')], default='No Data', max_length=20),
        ),
        migrations.AddField(
            model_name='area',
            name='processed',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Failed', 'Failed'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed')], default='No Data', max_length=20),
        ),
        migrations.AddField(
            model_name='area',
            name='registered',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Failed', 'Failed'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed')], default='No Data', max_length=20),
        ),
        migrations.AddField(
            model_name='area',
            name='uploaded',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Failed', 'Failed'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed')], default='No Data', max_length=20),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
