# Generated by Django 3.2.21 on 2023-11-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0017_auto_20231101_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='scans',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ship',
            name='contract_number',
            field=models.IntegerField(default=0),
        ),
    ]
