# Generated by Django 3.2.21 on 2023-11-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0018_auto_20231106_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='aligned',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Failed', 'Failed'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='area',
            name='cleaned',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Failed', 'Failed'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='area',
            name='exported',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Failed', 'Failed'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='area',
            name='imported',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Failed', 'Failed'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='area',
            name='point_cloud',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Failed', 'Failed'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='area',
            name='processed',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Failed', 'Failed'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='area',
            name='registered',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Failed', 'Failed'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='area',
            name='uploaded',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Failed', 'Failed'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed')], default='Completed', max_length=20),
        ),
    ]
