# Generated by Django 3.2.21 on 2023-11-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0021_alter_area_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Priority 0'), (1, 'Priority 1'), (2, 'Priority 2'), (3, 'Priority 3')], default=0),
        ),
    ]
