# Generated by Django 3.2.21 on 2023-11-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0022_alter_area_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='area',
            name='point_cloud_size',
            field=models.IntegerField(default=0),
        ),
    ]
