# Generated by Django 3.2.21 on 2023-11-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0023_auto_20231124_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='file_size',
            new_name='exported_size',
        ),
        migrations.AddField(
            model_name='area',
            name='processed_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='area',
            name='raw_size',
            field=models.IntegerField(default=0),
        ),
    ]
