# Generated by Django 3.2.21 on 2023-11-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0024_auto_20231127_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='exported_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='area',
            name='processed_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='area',
            name='raw_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
