# Generated by Django 3.2.21 on 2023-11-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0025_auto_20231127_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='point_cloud_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
