# Generated by Django 3.2.21 on 2023-12-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0026_alter_area_point_cloud_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Priority 0'), (1, 'Priority 1'), (2, 'Priority 2'), (3, 'Priority 3')], default=2),
        ),
        migrations.AlterField(
            model_name='area',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Priority 0'), (1, 'Priority 1'), (2, 'Priority 2'), (3, 'Priority 3')], default=2),
        ),
    ]
