# Generated by Django 3.2.21 on 2024-02-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0027_auto_20231204_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='machine',
            field=models.CharField(choices=[('Machine 1', 'Machine 1'), ('Machine 2', 'Machine 2'), ('Machine 3', 'Machine 3'), ('-', '-')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='area',
            name='aligned',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Minor Fail', 'Minor Fail'), ('Major Fail', 'Major Fail'), ('Critical Fail', 'Critical Fail'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed'), ('Hold', 'Hold'), ('Not Required', 'Not Required')], default='Queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='area',
            name='cleaned',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Minor Fail', 'Minor Fail'), ('Major Fail', 'Major Fail'), ('Critical Fail', 'Critical Fail'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed'), ('Hold', 'Hold'), ('Not Required', 'Not Required')], default='Queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='area',
            name='exported',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Minor Fail', 'Minor Fail'), ('Major Fail', 'Major Fail'), ('Critical Fail', 'Critical Fail'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed'), ('Hold', 'Hold'), ('Not Required', 'Not Required')], default='Queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='area',
            name='imported',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Minor Fail', 'Minor Fail'), ('Major Fail', 'Major Fail'), ('Critical Fail', 'Critical Fail'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed'), ('Hold', 'Hold'), ('Not Required', 'Not Required')], default='Queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='area',
            name='point_cloud',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Minor Fail', 'Minor Fail'), ('Major Fail', 'Major Fail'), ('Critical Fail', 'Critical Fail'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed'), ('Hold', 'Hold'), ('Not Required', 'Not Required')], default='Queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='area',
            name='processed',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Minor Fail', 'Minor Fail'), ('Major Fail', 'Major Fail'), ('Critical Fail', 'Critical Fail'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed'), ('Hold', 'Hold'), ('Not Required', 'Not Required')], default='Queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='area',
            name='registered',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Minor Fail', 'Minor Fail'), ('Major Fail', 'Major Fail'), ('Critical Fail', 'Critical Fail'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed'), ('Hold', 'Hold'), ('Not Required', 'Not Required')], default='Queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='area',
            name='uploaded',
            field=models.CharField(choices=[('No Data', 'No Data'), ('Legacy', 'Legacy'), ('Minor Fail', 'Minor Fail'), ('Major Fail', 'Major Fail'), ('Critical Fail', 'Critical Fail'), ('Queued', 'Queued'), ('WIP', 'WIP'), ('Completed', 'Completed'), ('Hold', 'Hold'), ('Not Required', 'Not Required')], default='Queued', max_length=20),
        ),
    ]
