# Generated by Django 3.2.21 on 2024-02-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0028_auto_20240215_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='machine',
            new_name='processing_machine',
        ),
    ]
