# Generated by Django 3.2.21 on 2024-02-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0030_machine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
