# Generated by Django 3.2.21 on 2024-02-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0032_auto_20240219_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='machine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
