# Generated by Django 3.2.21 on 2024-02-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0033_area_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='machine',
        ),
        migrations.AddField(
            model_name='area',
            name='processing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front_end.machine'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ship',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Priority 0'), (1, 'Priority 1'), (2, 'Priority 2'), (3, 'Priority 3'), (4, 'Priority 4')], default=2),
        ),
    ]
