# Generated by Django 3.2.21 on 2024-02-19 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0035_auto_20240219_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='processing',
        ),
        migrations.AddField(
            model_name='machine',
            name='ship',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='front_end.ship'),
        ),
    ]
