# Generated by Django 3.2.21 on 2024-02-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0037_auto_20240219_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='processing_capacity',
            field=models.DecimalField(decimal_places=0, default=0.5, max_digits=3),
            preserve_default=False,
        ),
    ]
