# Generated by Django 3.2.21 on 2024-02-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0040_alter_machine_processing_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='time_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
