# Generated by Django 3.2.21 on 2024-03-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0041_area_time_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='time_remaining',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
