# Generated by Django 3.2.21 on 2024-04-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0042_alter_area_time_remaining'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE front_end_area DROP COLUMN processing_machine;",
            reverse_sql=migrations.RunSQL.noop
        )
    ]
