# Generated by Django 3.2.21 on 2024-04-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0044_ship_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='aligned',
        ),
        migrations.RemoveField(
            model_name='area',
            name='imported',
        ),
        migrations.AddField(
            model_name='ship',
            name='time_remaining',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
