# Generated by Django 3.2.21 on 2024-04-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0045_auto_20240423_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ships', models.IntegerField(default=0)),
                ('total_areas', models.IntegerField(default=0)),
            ],
        ),
    ]
