# Generated by Django 3.2.21 on 2024-04-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0046_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='total_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
