# Generated by Django 3.2.21 on 2024-04-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0047_statistics_total_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='total_areas',
            new_name='total_scans',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='total_ships',
        ),
    ]
