# Generated by Django 3.2.21 on 2024-04-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0048_auto_20240426_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='completed_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='statistics',
            name='average_areas_per_ship',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='statistics',
            name='average_completion_time_per_ship',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='statistics',
            name='average_scans_per_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='statistics',
            name='average_scans_per_ship',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
