# Generated by Django 3.2.21 on 2024-04-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0049_auto_20240426_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='total_scans',
            field=models.IntegerField(default=0),
        ),
    ]
