# Generated by Django 3.2.21 on 2024-05-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0050_ship_total_scans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scanner', models.CharField(choices=[('red', 'red'), ('blue', 'blue')], max_length=10)),
            ],
        ),
    ]
