# Generated by Django 3.2.21 on 2024-05-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0051_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='scanner',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('both', 'both')], max_length=10),
        ),
    ]
