# Generated by Django 3.2.21 on 2024-05-03 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front_end', '0053_auto_20240503_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
