# Generated by Django 3.2.21 on 2024-05-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0057_alter_booking_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='users',
        ),
    ]
