# Generated by Django 3.2.21 on 2024-06-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0060_pagevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='time_remaining',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
