# Generated by Django 3.2.21 on 2024-06-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0061_pagevisit_time_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='calcualted_priority',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
