# Generated by Django 3.2.21 on 2024-06-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0062_auto_20240607_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='process_status_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='area',
            name='ship_area_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='area',
            name='calcualted_priority',
            field=models.IntegerField(default=0),
        ),
    ]
