# Generated by Django 3.2.21 on 2024-06-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0063_auto_20240607_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='calcualted_priority',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
