# Generated by Django 3.2.21 on 2024-07-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0064_alter_area_calcualted_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='process_status_priority',
        ),
        migrations.RemoveField(
            model_name='area',
            name='ship_area_priority',
        ),
        migrations.AddField(
            model_name='ship',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='area',
            name='calcualted_priority',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=10, null=True),
        ),
    ]
