# Generated by Django 3.2.21 on 2024-07-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0066_statistics_total_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
