# Generated by Django 3.2.21 on 2024-07-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0068_auto_20240704_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='average_exported_storage_per_ship',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='statistics',
            name='average_processed_storage_per_ship',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='statistics',
            name='average_raw_storage_per_ship',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
