# Generated by Django 3.2.21 on 2024-07-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0069_auto_20240708_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=200)),
                ('storage_capacity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('storage_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('storage_available', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
