# Generated by Django 3.2.21 on 2024-07-22 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0070_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front_end.ship'),
        ),
    ]
