# Generated by Django 3.2.21 on 2024-07-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0072_ship_contains_not_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='max_stars',
            field=models.BooleanField(default=False),
        ),
    ]
