# Generated by Django 3.2.21 on 2024-07-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0073_ship_max_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
