# Generated by Django 3.2.21 on 2024-07-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0074_ship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='survey_completed',
            field=models.BooleanField(default=False),
        ),
    ]
