# Generated by Django 3.2.21 on 2024-08-21 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0078_auto_20240821_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contract_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_manager', to='front_end.contractmanager'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer', to='front_end.designer'),
        ),
    ]
