# Generated by Django 3.2.21 on 2024-09-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0081_auto_20240823_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='average_error',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='area',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='max_error',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='area',
            name='min_overlap',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='point_cloud_created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
