# Generated by Django 3.2.21 on 2025-01-15 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0086_issuecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='front_end.issuecategory'),
        ),
    ]
