# Generated by Django 3.2.21 on 2025-01-17 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0087_issues_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
