# Generated by Django 3.2.21 on 2025-01-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0088_alter_issues_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='time_lost',
            field=models.DecimalField(blank=True, decimal_places=2, default=15, max_digits=5, null=True),
        ),
    ]
